### ISSUE TITLE
Cannot edit 

### ISSUE THREAD

**Issue by mikelantzelo** [Intronet/brackets-website-admin#5]
When I Open a html file from server... I can not edit...

**Comment by Intronet** [comment]
**Please elaborate** - "I can not edit" gives me nothing to go by
Appropriate responses as follows: -  
- text is unselectable
- modal dialog window will not close
- file is readonly

Send me a screengrab 

Sorry - I have not been able to maintain this extension
I will be back onto it soon

**Comment by mikelantzelo** [comment]
Everything is working fine!!! Thank you!!!

**Comment by x-civix-x** [comment]
Hi ! i've got the same probleme ! When i open a file HTML it's show me a preview of the page, not the editing code texte. How can i edit it ? Thanks !
